openapi: 3.0.3
info:
  title: Hlasování API
  description: |-
    API Hlasování umožňuje hůasovat v různých anketách.
  contact:
    email: filip@jirsak.org
  version: 1.0.0
servers:
  - url: https://hlasovani.czechitas.dev/api/
  - url: http://localhost:8000/api/
paths:
  /poll/{pollId}:
    parameters:
    - name: pollId
      in: path
      description: Identifikátor zvolené ankety.
      required: true
      schema:
        type: number
    get:
      summary: Načte výsledky jedné konkrétní ankety.
      responses:
        '200':
          description: Výsledky zvolené ankety.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
        '404':
          description: Anketa s uvedeným identifikátorem neexistuje.
    post:
      summary: Odešle hlas do dané ankety.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Vote"
      responses:
        '201':
          description: Hlas v anketě byl zaznamenán.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoteFull'
        '400':
          description: Chybná data.
        '404':
          description: Anketa s daným ID neexistuje.
components:
  schemas:
    Poll:
      type: array
      items:
        $ref: '#/components/schemas/PollItem'
    PollItem:
      type: object
      properties:
        option:
          type: string
        voters:
          type: array
          items:
            type: string
      required:
        - option
        - voters
    Vote:
      type: object
      properties:
        name:
          type: string
        option:
          type: number
      required:
        - name
        - option
    VoteFull:
      $ref: '#/components/schemas/Vote'
      type: object
      properties:
        id:
          type: string
      required:
        - id